server:
  port: 8089

    #eureka:
    # client:
    #  serviceUrl:
  #   defaultZone: ${EUREKA_URI:http://registry:8761/eureka}

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  prefix: /api
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    ocr:
      path: /ocr/**
      serviceId: ocrservice
      stripPrefix: false
      sensitiveHeaders:
