spring:
  application:
    name: app
  profiles:
    active: dev
  cloud:
    config:
      failFast: true
      uri: http://localhost:8888
      username: user
      password: test
      retry:
        initialInterval: 12000
        maxInterval: 12000
        maxAttempts: 30

server:
  port: 8081
