logging:
  level:
    org:
      springframework: ERROR
jwt:
  secret: javainuse

server:
  port: 9999
  servlet:
    context-path: /auth
    #ssl:
    # key-alias: focare
    # key-store: classpath:keystore/focare.p12
    # key-store-password: 123456
    # key-store-type: PKCS12

spring:
  application:
    name: auth
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:focare
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialize: true
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
