version: "3.2"

services:
  app:
      build: ../src/app-view
      ports:
          - "8081:8081"
      container_name: app
      depends_on:
        - "rabbitmq"
      command: >
      /bin/bash -c "
        sleep 5;
        nc -lk 0.0.0.0 8080;
      "

  rabbitmq:
      image: rabbitmq:3.5.4-management
      ports:
          - "5672:5672"
          - "15672:15672"
      container_name: rabbitmq
