version: "3.2"

services:
      rabbitmq:
      image: rabbitmq:3.5.4-management
      ports:
          - "5672:5672"
          - "15672:15672"
      container_name: rabbitmq
      
    mongodb:
      image: mongo:3
      ports:
         - "27017:27017"
      container_name: mongodb
