server:
  port: 8761
spring:
  application:
    name: registry
  cloud:
    config:
      uri: http://config:8888
      username: admin
      password: admin

#Eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false