# -Drun.profiles=dev
#-Dspring.profiles.active=prod
spring:
  application:
    name: config
  cloud:
  profiles:
    active: native
    config:
      server:
        native:
          searchLocations: classpath:/
        #git:
        #  uri: https://github.com/apedrina/config.git

server:
  port: 8888

security:
  user:
    password: test


