# -Drun.profiles=dev
#-Dspring.profiles.active=prod
spring:
  profiles:
    active: native
  application:
    name: config
  security:
   user:
    password: test
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
server:
  port: 8888




