server:
  port: 8082
  contextPath: /client

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
ribbon:
  eureka:
    enabled: true

client:
  queue:
    name: client_queue
    consumers:
      min: 1
      max: 3
  exchange:
    name: client_exchange

spring:
  cloud:
    config:
      failFast: true
      uri: http://localhost:8888
      username: user
      password: test
      retry:
        initialInterval: 12000
        maxInterval: 12000
        maxAttempts: 30
  rabbitmq:
    port: 5672
    host: localhost
    user: guest
    password: guest
    backoffpolicy:
      interval:
        initial: 1000
        max: 60000
  data:
    mongodb:
      host: mongodb
      database: client

  boot:
    admin:
      url: http://localhost:1111
      username: admin
      password: admin123

management:
  security:
    enabled: false

security:
  basic:
    user: test
    password: test
