server:
  port: 8089

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eureka:
    enabled: true

management:
  security:
    enabled: false

#ZUUL
zuul:
  prefix: /api
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    order:
        path: /order/**
        serviceId: order
        stripPrefix: false
        sensitiveHeaders:
    integration:
        path: /integration/**
        serviceId: integ
        stripPrefix: false
        sensitiveHeaders:
    client:
        path: /client/**
        serviceId: client
        stripPrefix: false
        sensitiveHeaders:
