#APP
server:
  port: 8999

logging:
  level:
    root: INFO

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#RIBBON
ribbon:
  eureka:
    enabled: false

#SEC
management:
  security:
    enabled: false

#SPRING
spring:
  #H2
  h2:
    console:
      consoleTimeout: 180000
      enabled: true

  #RABBIT
  rabbitmq:
    port: 5672
    host: localhost
    user: guest
    password: guest
    backoffpolicy:
      interval:
        initial: 1000
        max: 60000
  #DB
  datasource:
    plataform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  #JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
          ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#OTHER'S
client:
  queue:
    name: client_queue
    consumers:
      min: 1
      max: 3
  exchange:
    name: client_exchange
order:
  queue:
    name: order_queue
    consumers:
      min: 1
      max: 3
  exchange:
    name: order_exchange
