server:
  port: 8083

order:
  queue:
    name: order_queue
    consumers:
      min: 1
      max: 3
  exchange:
    name: order_exchange

spring:
  rabbitmq:
    port: 5672
    host: rabbitmq
    user: guest
    password: guest
    backoffpolicy:
      interval:
        initial: 1000
        max: 60000
  data:
    mongodb:
      host: mongodb
      database: order
  boot:
    admin:
      url: http://admin:1111
      username: admin
      password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry:8761/eureka}
ribbon:
  eureka:
    enabled: true
